### ISSUE TITLE
PINN on TF2.0 - callback API change needed

### ISSUE THREAD

**Issue by fabiononato** [PML-UCF/pinn#2]
The API for callbacks in `model.fit` method has changed in TF2.0. The Sample python script `run01_train_cumulative_damage.py` needs modification on `callbacks` to work.

https://github.com/PML-UCF/pinn/blob/master/samples/cumulative_damage/airplane_fleet_crack_growth/run01_train_cumulative_damage.py#L130

**Comment by renatogn** [comment]
Issue fixed on release v0.0.2 #5
